<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */

namespace MSbios\Media\Doctrine;

/** @var \Zend\Form\Form $form */
$form = $this->search;
$form->prepare();
$form->setAttribute('class', 'row');
?>

    <h1><?= __NAMESPACE__; ?></h1>

<?= $this->form()->openTag($form->setAttributes([
    'class' => 'row',
    'role' => 'form'
])); ?>

    <div class="col-sm-8 media-main">

        <div class="form-group">

            <?= $this->formElement($form->get('title')->setAttributes([
                'class' => 'form-control',
                'placeholder' => 'Start typing the news title (at least 3 characters)'
            ])); ?>

        </div>

        <?php if ($this->paginator->count()): ?>
            <?php foreach ($this->paginator as $item): ?>
                <div class="media-post">
                    <h2 class="blog-post-title">
                        <a href="<?= $this->url('home/news/view', ['id' => $item->getId(), 'slug' => $item->getSlug()]); ?>">
                            <?= $item->getTitle(); ?>
                        </a>
                    </h2>
                    <p class="blog-post-meta">
                        <?= $this->dateFormat(
                            $item->getPostdate(),
                            \IntlDateFormatter::MEDIUM,
                            \IntlDateFormatter::SHORT);
                        ?>
                        <a href="#"><?= $item->getCreator()->getUsername(); ?></a>
                    </p>

                    <?= $item->getContent(); ?>

                </div><!-- /.blog-post -->
            <?php endforeach; ?>

            <nav>
                <ul class="pager">
                    <li><a href="#">Previous</a></li>
                    <li><a href="#">Next</a></li>
                </ul>
            </nav>
        <?php else: ?>
            <div class="alert alert-info">
                There is not a single post
            </div>
        <?php endif; ?>

    </div><!-- /.blog-main -->

    <div class="col-sm-3 col-sm-offset-1 blog-sidebar">

        <div class="sidebar-module sidebar-module-inset">
            <h4>Registration date</h4>

            <?php $postdate = $form->get('postdate'); ?>

            <div class="form-group">
                <label for="date-from" class="control-label">Date from</label>
                <?= $this->formElement($postdate->get('from')->setAttributes([
                    'id' => 'date-from',
                    'class' => 'form-control',
                    'placeholder' => 'Date from'
                ])); ?>

            </div>
            <div class="form-group">
                <label for="date-to" class="control-label">Date to</label>
                <?= $this->formElement($postdate->get('to')->setAttributes([
                    'id' => 'date-to',
                    'class' => 'form-control',
                    'placeholder' => 'Date to'
                ])); ?>
            </div>
        </div>

        <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet
                fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
        </div>
        <div class="sidebar-module">
            <h4>Archives</h4>
            <ol class="list-unstyled">
                <li><a href="#">March 2014</a></li>
                <li><a href="#">February 2014</a></li>
                <li><a href="#">January 2014</a></li>
                <li><a href="#">December 2013</a></li>
                <li><a href="#">November 2013</a></li>
                <li><a href="#">October 2013</a></li>
                <li><a href="#">September 2013</a></li>
                <li><a href="#">August 2013</a></li>
                <li><a href="#">July 2013</a></li>
                <li><a href="#">June 2013</a></li>
                <li><a href="#">May 2013</a></li>
                <li><a href="#">April 2013</a></li>
            </ol>
        </div>
        <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
                <li><a href="#">GitHub</a></li>
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Facebook</a></li>
            </ol>
        </div>
    </div><!-- /.blog-sidebar -->

<?= $this->form()->closeTag($form); ?>